### ISSUE TITLE
Localcopy broken

### ISSUE THREAD

**Issue by Ede123** [lehner/LocalCopy#7]
I get the following error with JabRef 2.11b4 on Windows 7 x64 with Java 8 Update 60:

```
INFO: plug-in started - localcopy@2.6.0 (active/total: 3 of 3)
Exception in thread "main" java.lang.NoSuchMethodError: localcopy.LocalCopySidePaneComponent.setContent(Ljava/awt/Component;)V
    at localcopy.LocalCopySidePaneComponent.<init>(LocalCopyPane.java:219)
    at localcopy.LocalCopyPane.getSidePaneComponent(LocalCopyPane.java:578)
    at net.sf.jabref.JabRef.startSidePanePlugins(Unknown Source)
    at net.sf.jabref.JabRef.openWindow(Unknown Source)
    at net.sf.jabref.JabRef.start(Unknown Source)
    at net.sf.jabref.JabRefMain.main(Unknown Source)
```

**Comment by wbrenna** [comment]
I think this is a duplicate of bug #6.

**Comment by Ede123** [comment]
Yes actually it is (I overlooked the older issue because it was closed).

However I don't think plugins are unsupported in JabRef 3.11. Where did you get this information @minkkinen?

The only information I found were comments that support for plugins would be dropped in an upcoming JabRef version 3.80 which I don't seem to be able to find anywhere. Maybe @stefan-kolb or @koppor can comment on this?

**Comment by koppor** [comment]
The thing is that we refactored JabRef internally also in the 2.11 branch. Therefore, plugins broke even if we didn't remove the the plugin system in 2.11.

Unfortunately, LocalCopy will stop working with the release of 2.11 as we won't undo the refactorings. I suggest to wait for 2.80 as a similar functionality will be integrated. See https://github.com/JabRef/jabref/pull/101.

For a general discussion see https://github.com/JabRef/jabref/issues/152.

I know that this is not the answer you wanted to hear, but maybe it helps nevertheless.

**Comment by Ede123** [comment]
I see... Is it possible to fix plugins with reasonable effort to work with 2.11 branch?

What's the timeline for 2.80 (i.e. does it even make sense to bother to support 2.11 or will it be replaced by 2.80 swiftly)?

**Comment by koppor** [comment]
On the one hand, it is possible to fix plugins as we mostly moved classes without major rewrites. On the other hand, the functionality should be integrated in 2.80 as 2.11 will be a unmaintained branch.

We plan to release v2.80 shortly after v2.11 as Mac OS X support is broken in v2.11. However, we don't have a concrete release date, but target end of this year the latest.

**Comment by Ede123** [comment]
Great! I'll just stick with 2.10 then until 2.80 is out...
